### ISSUE TITLE
fix linux zen

### ISSUE THREAD

**Issue by xAffan** [nitanmarcel/waydroid-magisk#9] opened 2023-06-22 16:53 UTC
**Is your feature request related to a problem? Please describe.**
magisk cant work on linux zen kernal (N/A)

**Describe the solution you'd like**
magisk should work ( not sure why it doesnt work anyways )

**Describe alternatives you've considered**
switch to xanmod kernel but it is outdated compared to zen and you have to trust a random repo (chaotic aur)

**Additional context**

**Comment by nitanmarcel** [comment] 2023-06-22 17:56
Duplicate of https://github.com/nitanmarcel/waydroid-magisk/issues/3

**Comment by nitanmarcel** [comment] 2023-06-22 17:57
The issue is kernel related, there's nothing I can do about it.

**Closed by nitanmarcel** 2023-06-22 17:56 UTC
Labels: enhancement

**Comment by xAffan** [comment] 2023-06-22 21:36
Can you report this issue linux-zen kernel? I don't understand the issue so I can't do it.

**Comment by austinrojers** [comment] 2023-07-23 08:34
Hello @nitanmarcel,
How do you do?
What additional drivers does Xanmod have that works with Magisk?
Maybe we can add those drivers to other kernels as well?

Regard 
Austin
