### ISSUE TITLE
ERROR - Incomplete magisk setup

### ISSUE THREAD

**Issue by bocsi** [nitanmarcel/waydroid-magisk#13] opened 2023-08-08 22:25 UTC
running into this error when trying to install magi on waydroid: ERROR - Incomplete magisk setup

**To Reproduce**
1. Follow the install instructions under "From GitHub"
2.  run: sudo waydroid_magisk install --manager
3. Run waydroid_magisk setup after waydroid starts again
4. run: waydroid_magisk magiskhide enable
5. See error: ERROR - Incomplete magisk setup

**Logs**
From `sudo waydroid_magisk log --save`
[magisk_log_2023-08-08_15:16:02.log](https://github.com/nitanmarcel/waydroid-magisk/files/12296579/magisk_log_2023-08-08_15.16.02.log)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 38
- Waydroid Version: 1.4.1

**Additional context**
Installation:
`sudo waydroid_magisk install --manager `
[15:06:42] - INFO - Downloading Magisk Delta: canary-fdac22ba-delta
[15:06:42] - INFO - Extracting Magisk Delta
[15:06:42] - INFO - Installing Magisk Delta
[15:06:42] - INFO - Backing up bootanim.rc
[15:06:42] - INFO - Patching bootanim.rc
[15:06:42] - INFO - Finishing installation
[15:06:42] - INFO - Done
[15:06:42] - INFO - Run waydroid_magisk setup after waydroid starts again or install Magisk Delta Manager
[fedora@fedora modules]$ waydroid_magisk setup
[15:08:01] - ERROR - This command needs to be ran as a priviliged user!
[fedora@fedora modules]$ ` sudo !! `
` sudo waydroid_magisk setup `
No daemon is currently running!
No daemon is currently running!
No daemon is currently running!
No daemon is currently running!
No daemon is currently running!
No daemon is currently running!
[15:08:05] - INFO - Restarting Waydroid in 5 (press ^C to cancel)
[15:08:06] - INFO - Restarting Waydroid in 4 (press ^C to cancel)
[15:08:07] - INFO - Restarting Waydroid in 3 (press ^C to cancel)
[15:08:08] - INFO - Restarting Waydroid in 2 (press ^C to cancel)
[15:08:09] - INFO - Restarting Waydroid in 1 (press ^C to cancel)
[15:08:10] - INFO - Stopping Waydroid
[15:08:10] - INFO - Starting Waydroid
[fedora@fedora modules]$ ` waydroid_magisk magiskhide enable `
[15:09:31] - ERROR - Incomplete magisk setup

getting the same error if i run ` sudo waydroid_magisk magiskhide enable `

**Comment by bocsi** [comment] 2023-08-08 22:37
getting this new error now: ERROR - No daemon is currently running!

systemctl status waydroid_magisk_ota.service
● waydroid_magisk_ota.service - Waydroid Magisk OTA survival service
     Loaded: loaded (/usr/lib/systemd/system/waydroid_magisk_ota.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Tue 2023-08-08 14:45:14 PDT; 52min ago
   Main PID: 8153 (python3)
      Tasks: 1 (limit: 18777)
     Memory: 14.2M
        CPU: 405ms
     CGroup: /system.slice/waydroid_magisk_ota.service
             └─8153 python3 /usr/bin/waydroid_magisk --ota

Aug 08 14:45:14 fedora systemd[1]: Started waydroid_magisk_ota.service - Waydroid Magisk OTA survival service.

**Comment by nitanmarcel** [comment] 2023-08-09 06:31
What's the output of:

`sudo dmesg | grep magiskd -A 3`

**Comment by bocsi** [comment] 2023-08-10 16:52
this:
[ 1763.005849] DEBUG: pid: 54, tid: 54, name: magiskd  >>> magiskd <<<
[ 1763.005962] DEBUG: uid: 0
[ 1763.006052] DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
[ 1763.006149] DEBUG: Abort message: 'stack corruption detected (-fstack-protector)'
--
[ 2975.836773] DEBUG: pid: 54, tid: 54, name: magiskd  >>> magiskd <<<
[ 2975.836849] DEBUG: uid: 0
[ 2975.836930] DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
[ 2975.837028] DEBUG: Abort message: 'stack corruption detected (-fstack-protector)'

**Comment by nitanmarcel** [comment] 2023-08-10 17:45
Duplicate of https://github.com/nitanmarcel/waydroid-magisk/issues/3

**Closed by nitanmarcel** 2023-08-10 17:45 UTC

**Comment by bocsi** [comment] 2023-08-13 21:59
so with what kernel does this work? would be nice to add this in the prerequisites ...

**Comment by nitanmarcel** [comment] 2023-08-14 06:55
> so with what kernel does this work? would be nice to add this in the prerequisites ...

Same applies: https://github.com/nitanmarcel/waydroid-magisk#arch-linux

**Comment by bocsi** [comment] 2023-08-16 03:02
ok, i managed to get it working. the only thing that i'm not sure it's working is MagiskHide.
here is the output of ` waydroid_magisk magiskhide status ` 
[19:55:58] - ERROR - MagiskHide is enabled

and the output for ` sudo dmesg | grep magiskd -A 3 `
audit: type=1400 audit(1692151998.137:56): apparmor="ALLOWED" operation="file_lock" class="file" profile="lxc-waydroid" name="/sbin/.magisk/zygisk/261" pid=7179 comm="magiskd" requested_mask="k" denied_mask="k" fsuid=0 ouid=0
[  229.731872] init: Control message: Processed ctl.start for 'idmap2d' from pid: 260 (system_server)
[  229.921518] init: processing action (sys.sysctl.extra_free_kbytes=*) from (/system/etc/init/hw/init.rc:995)
[  230.658545] binder_debug: 10 callbacks suppressed

[  865.872527] audit: type=1400 audit(1692152634.719:63): apparmor="ALLOWED" operation="file_lock" class="file" profile="lxc-waydroid" name="/sbin/.magisk/zygisk/263" pid=10158 comm="magiskd" requested_mask="k" denied_mask="k" fsuid=0 ouid=0
[  866.366604] init: Control message: Processed ctl.start for 'idmap2d' from pid: 262 (system_server)
[  866.569638] init: processing action (sys.sysctl.extra_free_kbytes=*) from (/system/etc/init/hw/init.rc:995)
[  867.661016] binder_linux: undelivered TRANSACTION_COMPLETE

[ 2573.906246] audit: type=1400 audit(1692154342.752:70): apparmor="ALLOWED" operation="file_lock" class="file" profile="lxc-waydroid" name="/sbin/.magisk/zygisk/263" pid=21341 comm="magiskd" requested_mask="k" denied_mask="k" fsuid=0 ouid=0
[ 2574.864552] init: Control message: Processed ctl.start for 'idmap2d' from pid: 262 (system_server)
[ 2575.070466] init: processing action (sys.sysctl.extra_free_kbytes=*) from (/system/etc/init/hw/init.rc:995)
[ 2576.048254] binder_linux: undelivered TRANSACTION_COMPLETE

i also don't see the option for MagiskHide under the settings, see attached.
![Screenshot from 2023-08-15 20-00-56](https://github.com/nitanmarcel/waydroid-magisk/assets/60975283/74f409bf-0c58-4479-a014-fb010c5c4fd5)
![Screenshot from 2023-08-15 20-01-48](https://github.com/nitanmarcel/waydroid-magisk/assets/60975283/58f5e9cf-a997-4132-892b-89c8ba0c3627)

i'd greatly appreciate it if you can point me in the right direction as to what might be wrong.
Thank you.

**Comment by nitanmarcel** [comment] 2023-08-16 07:29
Ah right, he removed magisk hide and replaced it with umount modules. Press on it in the magisk manager to set it up I think?

No idea how it works as I moved to kernelsu on my phone

**Comment by bocsi** [comment] 2023-08-16 13:53
Ohh okay. i configured the apps i needed under there but wasn't sure it was doing anything.
