### ISSUE TITLE
waydroid_magisk setup fail

### ISSUE THREAD

**Issue by RSerejo** [nitanmarcel/waydroid-magisk#23] opened 2023-11-25 23:17 UTC
**Describe the bug**

**To Reproduce**
sudo pamac build waydroid_magisk
sudo waydroid_magisk install
sudo waydroid_magisk setup

![image](https://github.com/nitanmarcel/waydroid-magisk/assets/43152685/52b01998-4453-4a3a-a4aa-a8edc5a04cd0)

**Comment by dvoracekma2019** [comment] 2023-11-25 23:32
Same issue
![Screenshot from 2023-11-26 00-31-34](https://github.com/nitanmarcel/waydroid-magisk/assets/142264185/46badd4b-384c-4bb1-879c-fb2641030e3e)

**Comment by L0v3P01s0n** [comment] 2023-11-27 15:43
Can confirm the same happens to me

**Comment by rizzini** [comment] 2023-11-30 10:32
Same.

**Comment by nitanmarcel** [comment] 2023-11-30 16:02
I'll have to update the repo, there's already an opened issue.

Also marked as invalid since it seems that it uses pacman to build it since it's not supported here

**Closed by nitanmarcel** 2023-11-30 16:02 UTC
Labels: bug, invalid

**Comment by nitanmarcel** [comment] 2023-11-30 16:25
Update to the latest version to get latest changes.

Also as I said before there's not pacman script mainly because on some arch kernel this version of magisk is broken, update waydroid magisk from this repository.

**Comment by dvoracekma2019** [comment] 2023-11-30 21:06
I'm not using arch and pacman i'm using Fedora 39 with regular make install and still have the very same issue even with the new version. Could you please tell me on which kernel or linux distro does it work?

**Comment by nitanmarcel** [comment] 2023-12-01 04:42
> Yes yes I did ![Screenshot from 2023-11-30 22-54-01](https://private-user-images.githubusercontent.com/142264185/287081150-7eca9d89-f6fc-46f5-9c65-da64e595d849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDU4ODYsIm5iZiI6MTcwMTQwNTU4NiwicGF0aCI6Ii8xNDIyNjQxODUvMjg3MDgxMTUwLTdlY2E5ZDg5LWY2ZmMtNDZmNS05YzY1LWRhNjRlNTk1ZDg0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwNDM5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzIzNWM3NWIwMzIwMmJmYTkwNmU5NmFkMWI4NmQ3NTJjMmZiM2RjYTA0Y2Q5NTBiN2U5ODhkYWNhYzkyNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oQOKFo7ga0frjSwYGOtdzqM5qDLoq8_Rtb2c_wPjkNI) ![Screenshot from 2023-11-30 22-54-01](https://private-user-images.githubusercontent.com/142264185/287081195-8b50d973-6d36-4690-8b18-830f138f31f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDU4ODYsIm5iZiI6MTcwMTQwNTU4NiwicGF0aCI6Ii8xNDIyNjQxODUvMjg3MDgxMTk1LThiNTBkOTczLTZkMzYtNDY5MC04YjE4LTgzMGYxMzhmMzFmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwNDM5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNhNTQ0ODRiZWU0NTAxZjg1NTBiNzAwYmI1ZDRiMzI4ZjgzNGRjZjcxNDA0NTQ4NWY0YjYxNmFkNGI3Y2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dUmKR0kgKRakUeeCs_zspyx6RN5aevRwX-czY4acVRA)
> 
> What distro did you test it on? I would just set it up on that and then just copy all the waydroid files to Fedora

Also please follow the issue template so I can understand better what happens

https://github.com/nitanmarcel/waydroid-magisk/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by dvoracekma2019** [comment] 2023-12-01 09:22
**Describe the bug**
Installing KitsuneMask on waydroid fails, tried on Debian and fedora

**To reproduce**
sudo make install USE_SYSTEMD=1
![Screenshot from 2023-12-01 09-59-28](https://github.com/nitanmarcel/waydroid-magisk/assets/142264185/82d3255b-fe52-4ea0-b789-cb7900a212de)
sudo waydroid_magisk install --manager
![Screenshot from 2023-11-30 22-54-01](https://github.com/nitanmarcel/waydroid-magisk/assets/142264185/c31f7d0c-ee38-4461-8adf-02dfd24a13ff)
sudo waydroid_magisk setup
![Screenshot from 2023-12-01 10-02-10](https://github.com/nitanmarcel/waydroid-magisk/assets/142264185/8f101e62-f346-424c-b912-5b96296f47df)

**Other details**
![Screenshot from 2023-12-01 10-03-29](https://github.com/nitanmarcel/waydroid-magisk/assets/142264185/1b56cdfd-be25-4e59-a507-ed59092b5bd4)
when I remove it
![Screenshot from 2023-12-01 10-03-56](https://github.com/nitanmarcel/waydroid-magisk/assets/142264185/c99e912d-0e22-444a-a7ca-f141069c0595)
Always worked before november update.

**Comment by nitanmarcel** [comment] 2023-12-02 10:14
> **Describe the bug** Installing KitsuneMask on waydroid fails, tried on Debian and fedora
> 
> **To reproduce** sudo make install USE_SYSTEMD=1 ![Screenshot from 2023-12-01 09-59-28](https://private-user-images.githubusercontent.com/142264185/287219098-82d3255b-fe52-4ea0-b789-cb7900a212de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTIyMzMsIm5iZiI6MTcwMTUxMTkzMywicGF0aCI6Ii8xNDIyNjQxODUvMjg3MjE5MDk4LTgyZDMyNTViLWZlNTItNGVhMC1iNzg5LWNiNzkwMGEyMTJkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMDEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGRmOGMwZTY4NzQ0YTliOWU3NWU2MGFkMDkxYjZmYzNiMzAzNzE3NjE2M2NlMTM3ODU4MDQ4MzczZWRiOTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zBuZY_EPMyXZCjcrUhGGTx-J7QC3bxD5cazF_sLmirQ) sudo waydroid_magisk install --manager ![Screenshot from 2023-11-30 22-54-01](https://private-user-images.githubusercontent.com/142264185/287219540-c31f7d0c-ee38-4461-8adf-02dfd24a13ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTIyMzMsIm5iZiI6MTcwMTUxMTkzMywicGF0aCI6Ii8xNDIyNjQxODUvMjg3MjE5NTQwLWMzMWY3ZDBjLWVlMzgtNDQ2MS04YWRmLTAyZGZkMjRhMTNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMDEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzMzOGM0YTk1YjZkOTVlZjRiMGI0NDU3ZGVmOTdlYWM0MDhlMDcyZDFhNTNkMTg4N2I4MmJjMGNkOTZkYmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y6Dpggdy_JxNyUXECOoaqc2Fj-6k2i7QE5YC5hHJdp8) sudo waydroid_magisk setup ![Screenshot from 2023-12-01 10-02-10](https://private-user-images.githubusercontent.com/142264185/287219717-8f101e62-f346-424c-b912-5b96296f47df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTIyMzMsIm5iZiI6MTcwMTUxMTkzMywicGF0aCI6Ii8xNDIyNjQxODUvMjg3MjE5NzE3LThmMTAxZTYyLWYzNDYtNDI0Yy1iOTEyLTViOTYyOTZmNDdkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMDEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2M2M2RiZDhmMjk5N2FjZTUxMDUyZGRhNDU4ZDkyMjliYmZmYTQ0OTU5YzYyYWVkNmU5NzQ3OGFjM2Q1OTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UUC8GDiOoij3RwYUQAA-b1QxPdsudhEw9lQVSBjYglc)
> 
> **Other details** ![Screenshot from 2023-12-01 10-03-29](https://private-user-images.githubusercontent.com/142264185/287219958-1b56cdfd-be25-4e59-a507-ed59092b5bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTIyMzMsIm5iZiI6MTcwMTUxMTkzMywicGF0aCI6Ii8xNDIyNjQxODUvMjg3MjE5OTU4LTFiNTZjZGZkLWJlMjUtNGU1OS1hNTA3LWVkNTkwOTJiNWJkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMDEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzgyYjczODQyYjExNmQzNmRhODg1ODczNjI2MDNjMmU5MWYyNWY4OTAxZjMzYzhiZjY4OWZkZTM0MDk0NmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42gglnGHNGef4JzfzJhVqbh0IoIl0l36BXak-9PHPqw) when I remove it ![Screenshot from 2023-12-01 10-03-56](https://private-user-images.githubusercontent.com/142264185/287220072-c99e912d-0e22-444a-a7ca-f141069c0595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTIyMzMsIm5iZiI6MTcwMTUxMTkzMywicGF0aCI6Ii8xNDIyNjQxODUvMjg3MjIwMDcyLWM5OWU5MTJkLTBlMjItNDQ0YS1hN2NhLWYxNDEwNjljMDU5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMDEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGRmZDk2ZjE3YTBlODYxYjExNmQxOTYzNzdjOTVkZjBlNmIyYjZmODY1YzZkZDljOTcwOWE4M2RhYzM0NDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hut_I_UEEMIqaAqoYIg-Nferk0krw9uu_Gx7OyF6TCA) Always worked before november update.
> 
> I really appreciate all your work and effort on this project!!

No valuable information is given.

Start waydroid and run the log command as the issue template suggests. Also try to start clean.

https://github.com/nitanmarcel/waydroid-magisk/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by SX-9** [comment] 2024-02-07 01:29
![image](https://github.com/nitanmarcel/waydroid-magisk/assets/90962949/a38a031b-d767-4ada-aa46-e7c15f1ef628)
same issue on manjaro with waydroid GAPPS image
